package export

import (
	"bytes"
	"fmt"

	"github.com/jung-kurt/gofpdf"
	"go.uber.org/zap"
)

// PDFExporter exports data to PDF format
type PDFExporter struct {
	logger *zap.Logger
}

// NewPDFExporter creates a new PDF exporter
func NewPDFExporter(logger *zap.Logger) *PDFExporter {
	return &PDFExporter{
		logger: logger,
	}
}

// Export exports data to PDF format
func (e *PDFExporter) Export(data *ExportData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	// Title
	pdf.SetFont("Arial", "B", 20)
	pdf.CellFormat(0, 10, "DoneList Export", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	// Metadata section
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(0, 6, fmt.Sprintf("Exported: %s", data.Metadata.ExportedAt.Format("2006-01-02 15:04:05")), "", 1, "", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Format: PDF"), "", 1, "", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Total Records: %d", data.Metadata.TotalRecords), "", 1, "", false, 0, "")

	if data.Metadata.DateRange != nil {
		pdf.CellFormat(0, 6, fmt.Sprintf("Date Range: %s to %s",
			data.Metadata.DateRange.Start.Format("2006-01-02"),
			data.Metadata.DateRange.End.Format("2006-01-02")), "", 1, "", false, 0, "")
	}
	pdf.Ln(5)

	// Checkins section
	if len(data.Checkins) > 0 {
		pdf.SetFont("Arial", "B", 14)
		pdf.CellFormat(0, 8, "Checkins", "", 1, "", false, 0, "")
		pdf.Ln(2)

		for i, checkin := range data.Checkins {
			// Check if we need a new page
			if pdf.GetY() > 250 {
				pdf.AddPage()
			}

			// Checkin number and title
			pdf.SetFont("Arial", "B", 11)
			pdf.CellFormat(0, 6, fmt.Sprintf("%d. %s", i+1, checkin.Title), "", 1, "", false, 0, "")

			// Checkin details
			pdf.SetFont("Arial", "", 9)
			pdf.CellFormat(0, 5, fmt.Sprintf("   Category: %s", checkin.Category), "", 1, "", false, 0, "")
			pdf.CellFormat(0, 5, fmt.Sprintf("   Status: %s | Priority: %s", checkin.Status, checkin.Priority), "", 1, "", false, 0, "")

			if len(checkin.Tags) > 0 {
				tagsStr := ""
				for j, tag := range checkin.Tags {
					if j > 0 {
						tagsStr += ", "
					}
					tagsStr += tag
				}
				pdf.CellFormat(0, 5, fmt.Sprintf("   Tags: %s", tagsStr), "", 1, "", false, 0, "")
			}

			if checkin.Description != nil && *checkin.Description != "" {
				pdf.SetFont("Arial", "I", 9)
				// Use MultiCell for potentially long descriptions
				pdf.MultiCell(0, 5, fmt.Sprintf("   %s", *checkin.Description), "", "", false)
			}

			pdf.CellFormat(0, 5, fmt.Sprintf("   Created: %s | Updated: %s",
				checkin.CreatedAt.Format("2006-01-02 15:04"),
				checkin.UpdatedAt.Format("2006-01-02 15:04")), "", 1, "", false, 0, "")
			pdf.Ln(3)
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 10, fmt.Sprintf("Generated by DoneList - Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")

	// Output to bytes
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		e.logger.Error("Failed to generate PDF", zap.Error(err))
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}

	return buf.Bytes(), nil
}

// GetMimeType returns the MIME type for PDF
func (e *PDFExporter) GetMimeType() string {
	return "application/pdf"
}

// GetFileExtension returns the file extension for PDF
func (e *PDFExporter) GetFileExtension() string {
	return "pdf"
}
